/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aherreraz.usermanagement;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class UserManagementApplicationTests {
    @Test
    void contextLoads() {
    }
}